### ISSUE TITLE
about the collection: "collection.splitTitle.tsv"

### ISSUE THREAD

**Issue by xxfanfan** [Deriq-Qian-Dong/III-Retriever#1]
Hi, I'm training with your model, but I found a parameter passed into a collection file, and I can't find any clues about this collection file. How do I get the file passed by the collection parameter，thanks

**Comment by CSQianDong** [comment]
collection could be downloaded from RocketQA's [script](https://github.com/PaddlePaddle/RocketQA/blob/main/research/RocketQAv2_EMNLP2021/wget_data.sh). The format of collection.splitTitle.tsv is "pid\ttitle\tpassage\n" per line.
